// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxmdCtO1Uc5jn17-1AyZaz1tBdpBiK3uo',
    appId: '1:196778462251:web:ce11e9e81b0c960c1bae6e',
    messagingSenderId: '196778462251',
    projectId: 'rital-f2957',
    authDomain: 'rital-f2957.firebaseapp.com',
    storageBucket: 'rital-f2957.firebasestorage.app',
    measurementId: 'G-FHE00QXS19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBah6ypjebBagnByeTbvJ-o0ljKZliS7eA',
    appId: '1:196778462251:android:15745cbd5f15071f1bae6e',
    messagingSenderId: '196778462251',
    projectId: 'rital-f2957',
    storageBucket: 'rital-f2957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1vHPOLDoULw8gqUrvCjlfgTlwkir-8L4',
    appId: '1:196778462251:ios:36f4514fa395762f1bae6e',
    messagingSenderId: '196778462251',
    projectId: 'rital-f2957',
    storageBucket: 'rital-f2957.firebasestorage.app',
    iosBundleId: 'com.example.rital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1vHPOLDoULw8gqUrvCjlfgTlwkir-8L4',
    appId: '1:196778462251:ios:36f4514fa395762f1bae6e',
    messagingSenderId: '196778462251',
    projectId: 'rital-f2957',
    storageBucket: 'rital-f2957.firebasestorage.app',
    iosBundleId: 'com.example.rital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxmdCtO1Uc5jn17-1AyZaz1tBdpBiK3uo',
    appId: '1:196778462251:web:4b7b3f4131d3829c1bae6e',
    messagingSenderId: '196778462251',
    projectId: 'rital-f2957',
    authDomain: 'rital-f2957.firebaseapp.com',
    storageBucket: 'rital-f2957.firebasestorage.app',
    measurementId: 'G-N31KFT15P6',
  );
}
